apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  PORT: "8080"
  DB_HOST: "k8s-training-dev-postgres.xxxxx.us-east-1.rds.amazonaws.com"
  DB_NAME: "appdb"
  CACHE_TTL_SECONDS: "10"
  RATE_LIMIT_RPS: "100"
  CORS_ORIGINS: "*"
