---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-storage-class
provisioner: s3.csi.aws.com
parameters:
  mpc.kubernetes.io/bucketName: kubernetes-storage-bucket
mountOptions:
  - allow-delete
  - region us-east-1
reclaimPolicy: Retain
volumeBindingMode: Immediate

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-storage-class
  resources:
    requests:
      storage: 120Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-storage-class
  resources:
    requests:
      storage: 120Gi
